name: 'Terraform Workflow'

on:
  # push:
  #   branches:
  #     - master
  #     - workflow
  pull_request:
    branches:
      - master
      - workflow

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      # run: terraform plan
      # working-directory: ./terraform
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: './terraform'
        tf_actions_comment: true
      #   args: '-var-file="terraform.tfvars"'
      env:
        NAME: REMOVED
        TF_VAR_name: REMOVED
        USER: REMOVED
        TF_VAR_user: REMOVED
        PASSWORD: REMOVED
        TF_VAR_password: REMOVED

    - name: Terraform Apply
      # run: terraform apply -auto-approve
      # working-directory: ./terraform
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: './terraform'
        tf_actions_comment: true
        args: '-auto-approve=true'
      env:
        NAME: REMOVED
        TF_VAR_name: REMOVED
        USER: REMOVED
        TF_VAR_user: REMOVED
        PASSWORD: REMOVED
        TF_VAR_password: REMOVED

